### ISSUE TITLE
Miss some documentation for using SDK 

### ISSUE THREAD

**Issue by leccyril** [vector-im/hydrogen-web#838] opened 2022-08-10 13:07 UTC
Thanks for your great lib.

I wonder if it is possible to have more documentation about using SDK, here we only have one example , no explanations how to use it precisely etc.. because here we can only create a page with timeline but no left or right side no writing message etc...

**Comment by bwindels** [comment] 2022-08-25 08:04
Duplicate of #730

**Closed as completed by bwindels** 2022-08-25 08:04 UTC
