### ISSUE TITLE
Message Edits

### ISSUE THREAD

**Issue by fkwp** [vector-im/hydrogen-web#830] opened 2022-08-01 14:19 UTC
This is an epic issue. List of individual issues is below:

- [ ] As a user you would wish to be able to edit sent messages in the same way that you can on Element FOSS. link to ticket- [ ]

**Comment by ptman** [comment] 2022-09-30 06:54
#535

editing is now in latest spec

**Comment by bwindels** [comment] 2023-01-05 10:15
Duplicate of #535

**Closed as completed by bwindels** 2023-01-05 10:15 UTC
Labels: EPIC
