### ISSUE TITLE
Use hydrogen-sdk for embedded application is not working

### ISSUE THREAD

**Issue by leccyril** [vector-im/hydrogen-web#843] opened 2022-08-12 08:07 UTC
Hydrogen is really great to be embedded in differents projects and different technologies... but some issues are really annoying

**Describe the bug**
If on the main project we decide to create a lib build, automatically all assets will be parsed and inlined in 2 files
css file and js file, then for example other files will be omitted as download-sandbox.html wich causing 2 things 

1. Corrupted lib with missing files and bug
2. Big resources files (css 6Mo because embbed font and svg) and big js file

If we want o use it as an asset build it will create a html file and hashed resources in assets folder (so even if we want to use asset as it is it will not be possible because on each generation assets files will have new name)

In this folder we have several fonts and svg useless making folder quite big

**To Reproduce**

Create a new projet with vite library, choose to build normally (for creating asset folder)
or create a lib (the one we are aiming) ex:

    import vue from "@vitejs/plugin-vue";

    const path = require("path");

    const manifest = require( "./package.json" );
    const version = manifest.version;

    const config = {
	plugins: [vue()],
	build: {
		lib: {
			entry: path.resolve( __dirname, 'lib/main.js' ),
			formats: ['umd']
		},
	}
    };

    export default config;

where main.js is the entry point of the lib

**Expected behavior**
Lib packaging working with not inlined asset

Possible to use the normal assets as a lib (to not produce html file)

Is it possible to choose to not create hash on end of file ? to be able to use index.js, main.js freely where we want ? or it is possible to retrieve the hash for a file and to reuse it ? as i know each file have a different hash (because our system already process hash stuff)

could we for example override with our own css without using assets folder ?
possible to reduce the font number etc if we want only to use one? or own ?

the real advantage of hydrogen is to be able to be embbeded in application and to be real real light, otherwise element is the alternative but functionaly not really good hydrogen SDK is the best tool to make it !

**Comment by bwindels** [comment] 2022-08-16 12:29
Several things here:

> If on the main project we decide to create a lib build, automatically all assets will be parsed and inlined in 2 files
css file and js fil

the inlining of assets sounds like an issue with vite setup.

> we decide to create a lib build

Making other libraries that use the hydrogen-view-sdk is also not really an intended use, although I'm not sure why that wouldn't work. In any case, it's not something we can help you with as it would take too much of our time.

> In this folder we have several fonts and svg useless making folder quite big

We don't optimize for library disk size currently, as any app that builds on the hydrogen-view-sdk will discard any resources that it doesn't use.

> Is it possible to choose to not create hash on end of file ?

No, any file name that has a hash should not be considered a part of the public interface of the SDK, and are only meant to be referenced by other files in the SDK, but not outside of the SDK.


This is a lot of text. I'm not sure if there is any actual issue with the hydrogen sdk being reported here, but if there is, can you please file a more specific issue of what the problem is exactly?

Will close this for now.

**Closed as completed by bwindels** 2022-08-16 12:29 UTC
